name: PullRequest Tester

on:
  pull_request:

env:
  cache-name: cache-api-node-modules

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.detect-changes.outputs.frontend-changed }}
      backend-changed: ${{ steps.detect-changes.outputs.backend-changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for changes in splittr-frontend and splittr-backend
        id: detect-changes
        run: |
          FRONTEND_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^splittr-frontend/' || true)
          BACKEND_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^splittr-backend/' || true)
          
          echo "FRONTEND_CHANGED=${FRONTEND_CHANGED}" >> $GITHUB_ENV
          echo "BACKEND_CHANGED=${BACKEND_CHANGED}" >> $GITHUB_ENV
          
          echo "::set-output name=frontend-changed::${FRONTEND_CHANGED}"
          echo "::set-output name=backend-changed::${BACKEND_CHANGED}"

  cache-and-install:
    needs: check-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, backend]
    
    steps:
      - uses: actions/checkout@v4
        if: env.${{ matrix.component }}_CHANGED != ''

      - name: Set up Node.js for ${{ matrix.component }}
        if: env.${{ matrix.component }}_CHANGED != ''
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: splittr-${{ matrix.component }}/**/package-lock.json

      - name: Cache node modules for ${{ matrix.component }}
        id: cache-npm
        if: env.${{ matrix.component }}_CHANGED != ''
        uses: actions/cache@v4
        with:
          path: splittr-${{ matrix.component }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('splittr-${{ matrix.component }}/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies for ${{ matrix.component }}
        if: env.${{ matrix.component }}_CHANGED != ''
        run: npm install --prefix splittr-${{ matrix.component }}

  eslint-and-prettier-check:
    needs: cache-and-install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, backend]
    steps:
      - uses: actions/checkout@v4

      - name: Restore Dependencies for ${{ matrix.component }}
        uses: actions/cache@v4
        with:
          path: splittr-${{ matrix.component }}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('splittr-${{ matrix.component }}/**/package-lock.json') }}

      - name: Run ESLint and Prettier checks for ${{ matrix.component }}
        if: env.${{ matrix.component }}_CHANGED != ''
        run: |
          npm run eslint --prefix splittr-${{ matrix.component }} &
          eslint_pid=$!

          npm run prettier --prefix splittr-${{ matrix.component }} &
          prettier_pid=$!

          wait $eslint_pid
          eslint_exit_code=$?

          wait $prettier_pid
          prettier_exit_code=$?

          if [ $eslint_exit_code -ne 0 ] || [ $prettier_exit_code -ne 0 ]; then
            exit 1
          fi
