name: Build And Deploy To ECS

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: write
  checks: write
  actions: read

jobs:
  dev:
    concurrency:
      group: ${{ github.ref_name }}
    name: Build and deploy to dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::949263681218:role/dev-milan-splittr-api-github-action-role
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy to Dev
        run: |
          cd splittr-frontend
          npm install
          npm run build
          aws s3 sync build s3://splittr-webportal-dev
