name: Build And Deploy Frontend

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: write
  checks: write
  actions: read

jobs:
  dev:
    concurrency:
      group: ${{ github.ref_name }}
    name: Build and deploy to dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::949263681218:role/web-portal-milan-splittr-github-action-role
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: Fetch and export secrets
        id: fetch_secrets
        run: |
          aws secretsmanager get-secret-value --secret-id dev-web-portal | jq -r '.SecretString' > secrets.json
          while IFS="=" read -r key value; do
            echo "${key}=${value}" >> $GITHUB_ENV
          done < <(jq -r 'to_entries[] | "\(.key)=\(.value)"' secrets.json)

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy to Dev
        run: |
          cd splittr-frontend
          npm install
          npm run build
          aws s3 sync dist s3://milan-splittr-web-portal
